import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Footer } from "@/components/common/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import FiltersProvider from "@/providers/FiltersProvider";
import TanstackQueryProvider from "@/providers/TanstackQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <TanstackQueryProvider>
          <FiltersProvider>
            <Navbar />
            <div className="md:pt-24 pt-20">
              {children}
            </div>
            <Footer />
          </FiltersProvider>
          <ReactQueryDevtools />
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
