# Generated by Django 5.0.2 on 2025-10-26 19:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "external_link",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("price", models.FloatField()),
                ("negotiable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "additional_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="listings_favorited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="marketplace/images")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="market.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="market.listing"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="buyers",
            field=models.ManyToManyField(
                blank=True,
                related_name="listings_offered",
                through="market.Offer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="tags",
            field=models.ManyToManyField(blank=True, to="market.tag"),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "recommended_attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="types_recommended",
                        to="market.attribute",
                    ),
                ),
                (
                    "required_attributes",
                    models.ManyToManyField(
                        blank=True, related_name="types_required", to="market.attribute"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="market.type"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["user"], name="market_offe_user_id_48d792_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["listing"], name="market_offe_listing_17ac99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["created_at"], name="market_offe_created_e6ee0e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_offer_market"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["title"], name="market_list_title_bec7ee_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="market_list_price_3a149f_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["created_at"], name="market_list_created_b80a0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["expires_at"], name="market_list_expires_159da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["negotiable"], name="market_list_negotia_bf5de1_idx"
            ),
        ),
    ]
