# Generated by Django 5.0.2 on 2025-11-01 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Sublet",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="market.listing",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("beds", models.PositiveIntegerField()),
                ("baths", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            bases=("market.listing",),
        ),
        migrations.RemoveField(
            model_name="type",
            name="recommended_attributes",
        ),
        migrations.RemoveField(
            model_name="type",
            name="required_attributes",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="type",
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="listing",
            name="additional_data",
        ),
        migrations.AddField(
            model_name="listingimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="offer",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_received",
                to="market.listing",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="market.listing",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("LIKE_NEW", "Used - Like New"),
                            ("GOOD", "Used - Good"),
                            ("FAIR", "Used - Fair"),
                        ],
                        default="NEW",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="market.category",
                    ),
                ),
            ],
            bases=("market.listing",),
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
