# Generated by Django 5.0.2 on 2026-01-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="offer",
            name="message",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
