# Generated by Django 5.0.2 on 2026-01-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_alter_user_options_alter_offer_message"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneVerification",
        ),
    ]
