# Generated by Django 5.0.2 on 2025-11-13 03:29

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_category_sublet_remove_type_recommended_attributes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="offer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
