# Generated by Django 5.0.2 on 2026-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_delete_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
