# Generated by Django 5.0.2 on 2026-02-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_delete_phoneverification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sublet",
            old_name="address",
            new_name="street_address",
        ),
        migrations.AlterField(
            model_name="listing",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
