# Generated by Django 5.0.2 on 2026-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_rename_address_sublet_street_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
