# Generated by Django 5.0.2 on 2026-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_rename_address_sublet_street_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sublet",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sublet",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
