# Generated by Django 5.0.2 on 2026-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_sublet_true_latitude_sublet_true_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="market_list_status_0933cf_idx"),
        ),
    ]
