# Generated by Django 5.0.2 on 2026-09-25 21:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_sublet_true_latitude_sublet_true_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "rating_type",
                    models.CharField(
                        choices=[
                            ("BUYER", "Buyer Rating"),
                            ("SELLER", "Seller Rating"),
                        ],
                        default="BUYER",
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="market.listing",
                    ),
                ),
                (
                    "reviewed_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["reviewer"], name="market_rati_reviewe_010d38_idx"
                    ),
                    models.Index(
                        fields=["reviewed_user"], name="market_rati_reviewe_e0f8de_idx"
                    ),
                    models.Index(
                        fields=["listing"], name="market_rati_listing_7deff6_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="market_rati_created_99ab89_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "reviewed_user", "listing"),
                name="unique_rating_market",
            ),
        ),
    ]
