# Generated by Django 5.0.2 on 2026-03-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_listing_status_listing_market_list_status_0933cf_idx"),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("market", "Listing")
            .objects.all()
            .update(status="APPROVED"),
            migrations.RunPython.noop,
        ),
    ]
