# Generated by Django 5.0.2 on 2025-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0009_item_market_item_title_c9d008_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="additional_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="recommended_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="categories_recommended", to="market.attribute"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="required_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="categories_required", to="market.attribute"
            ),
        ),
    ]
